# Generated by Django 5.2.1 on 2025-06-23 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(max_length=60)),
                ('subject_code', models.TextField(max_length=20)),
                ('dateandtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Assign_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(max_length=5)),
                ('subject_name', models.TextField(max_length=60)),
                ('subject_code', models.TextField(max_length=20)),
                ('dateandtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
