# Generated by Django 5.2.1 on 2025-06-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign_subjects',
            name='class_number',
            field=models.IntegerField(),
        ),
    ]
