# Generated by Django 5.2.1 on 2025-06-23 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0002_alter_assign_subjects_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_subjects',
            name='subject_type',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
