# Generated by Django 5.2.1 on 2025-06-24 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0003_assign_subjects_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_subjects',
            name='class_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
