# Generated by Django 5.2.1 on 2025-06-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0004_assign_subjects_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_subjects',
            old_name='subject_name',
            new_name='subject_code_name',
        ),
        migrations.RemoveField(
            model_name='assign_subjects',
            name='subject_code',
        ),
    ]
