# Generated by Django 5.2.1 on 2025-06-24 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0005_rename_subject_name_assign_subjects_subject_code_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_subjects',
            old_name='subject_code_name',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='assign_subjects',
            name='subject_code',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
