# Generated by Django 5.2.1 on 2025-06-30 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0006_rename_subject_code_name_assign_subjects_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('class_name', models.TextField(max_length=20)),
                ('roll_number', models.TextField(max_length=10)),
                ('gender', models.TextField(max_length=12)),
                ('first_name', models.TextField(max_length=50)),
                ('middle_name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
                ('father_name', models.TextField(max_length=60)),
                ('mother_name', models.TextField(max_length=60)),
                ('nationality', models.TextField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('religion', models.TextField(max_length=10)),
                ('category', models.TextField(max_length=15)),
                ('blood_group', models.TextField(max_length=5)),
                ('aadhaar_number', models.TextField(max_length=12)),
                ('full_address', models.TextField(max_length=250)),
                ('father_phone_number', models.TextField(max_length=15)),
                ('mother_phone_number', models.TextField(max_length=15)),
                ('guardian_phone_number', models.TextField(max_length=15)),
                ('father_email', models.EmailField(max_length=40)),
                ('mother_email', models.EmailField(max_length=40)),
                ('guardian_email', models.EmailField(max_length=40)),
                ('dateandtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
