# Generated by Django 5.2.1 on 2025-07-01 10:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0007_add_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_students',
            name='guardian_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
