# Generated by Django 5.2.1 on 2025-07-01 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0008_add_students_guardian_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_students',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='add_students',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='add_students',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='add_students',
            name='student_full_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
