# Generated by Django 5.2.1 on 2025-07-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0009_remove_add_students_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_Rollno_to_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('class_name', models.TextField(max_length=20)),
                ('roll_number', models.TextField(max_length=10)),
                ('gender', models.TextField(max_length=12)),
                ('student_full_name', models.TextField(max_length=200)),
                ('father_name', models.TextField(max_length=60)),
                ('guardian_name', models.TextField(max_length=60)),
                ('date_of_birth', models.DateField()),
                ('aadhaar_number', models.TextField(max_length=12)),
                ('father_phone_number', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
