# Generated by Django 5.2.1 on 2025-07-08 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0010_assign_rollno_to_students_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign_rollno_to_students',
            name='dateandtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
